variables:
    VPC_NETWORK_ONLY_ALERT_LIST:
        required: false
        type: array
        default:
        description: "Which rules would you like to run? Possible values are "
        description: "Which rules would you like to run? Possible values are "
        description: "Which rules would you like to run? Possible values are "
